# Docker compose 버전
version: "3.8"
# 가동할 컨테이너 목록
services:
  openvidu-server:
    image: openvidu/openvidu-server:2.19.0
    container_name: ccp_openvidu
    restart: on-failure
    network_mode: host
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - SERVER_SSL_ENABLED=false
      - SERVER_PORT=5443
      - KMS_URIS=["ws://localhost:8888/kurento"]
      - COTURN_REDIS_IP=127.0.0.1
      - COTURN_REDIS_PASSWORD=${OPENVIDU_SECRET}
      - COTURN_IP=${COTURN_IP:-auto-ipv4}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  kms:
    image: ${KMS_IMAGE:-kurento/kurento-media-server:6.16.0}
    container_name: ccp_kms
    restart: always
    network_mode: host
    ulimits:
      core: -1
    environment:
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=57000
      - GST_DEBUG=${KMS_DOCKER_ENV_GST_DEBUG:-}
      - KURENTO_LOG_FILE_SIZE=${KMS_DOCKER_ENV_KURENTO_LOG_FILE_SIZE:-100}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

  redis:
    image: openvidu/openvidu-redis:3.0.0
    container_name: ccp_redis
    restart: always
    network_mode: host
    environment:
      - REDIS_PASSWORD=${OPENVIDU_SECRET}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  coturn:
    image: openvidu/openvidu-coturn:5.0.0
    container_name: ccp_coturn
    restart: on-failure
    network_mode: host
    environment:
      - REDIS_IP=127.0.0.1
      - DB_NAME=0
      - DB_PASSWORD=${OPENVIDU_SECRET}
    command:
      - --log-file=stdout
      - --listening-port=3478
      - --fingerprint
      - --lt-cred-mech
      - --min-port=57001
      - --max-port=65535
      - --realm=openvidu
      - --verbose
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  nginx:
    image: openvidu/openvidu-proxy:7.0.0
    container_name: ccp_nginx
    restart: on-failure
    network_mode: host
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./owncert:/owncert
      - ./custom-nginx-vhosts:/etc/nginx/vhost.d/
    environment:
      - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
      - CERTIFICATE_TYPE=${CERTIFICATE_TYPE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - PROXY_HTTP_PORT=${HTTP_PORT:-}
      - PROXY_HTTPS_PORT=${HTTPS_PORT:-}
      - ALLOWED_ACCESS_TO_DASHBOARD=${ALLOWED_ACCESS_TO_DASHBOARD:-}
      - ALLOWED_ACCESS_TO_RESTAPI=${ALLOWED_ACCESS_TO_RESTAPI:-}
      - PROXY_MODE=CE
      - WITH_APP=true
      - SUPPORT_DEPRECATED_API=${SUPPORT_DEPRECATED_API:-true}
      - REDIRECT_WWW=${REDIRECT_WWW:-false}
      - WORKER_CONNECTIONS=${WORKER_CONNECTIONS:-10240}
      - PUBLIC_IP=${PROXY_PUBLIC_IP:-auto-ipv4}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
networks:
  back:
volumes:
  mysql-data:
  files:
